# -*- coding: utf-8 -*-
"""CarsNames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y4cvl-JREXDOV37qc-kKaA7veNIQH6H
"""

!unzip archive.zip

import pandas as pd

df = pd.read_csv('Cars in Movies.csv', sep=';')

df.shape

df.columns

df['Car Name'].nunique()

# translate all elements to English before matching

df['Car Name'].sample(10)

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

def get_matching_score(text1, text2):
    embeddings = model.encode([text1, text2])
    similarity = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return float(similarity)

# Example
score = get_matching_score("Toyota Camry 2020", "Toyota Camry 2020")
# Returns ~1.0 for perfect match

score

from fuzzywuzzy import fuzz
import re

def normalize_vehicle_text(text):
    # Remove extra spaces, special characters, standardize case
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text.lower())
    return ' '.join(text.split())

def fuzzy_match_score(text1, text2):
    normalized1 = normalize_vehicle_text(text1)
    normalized2 = normalize_vehicle_text(text2)

    # Combine multiple fuzzy matching techniques
    ratio = fuzz.ratio(normalized1, normalized2)
    partial_ratio = fuzz.partial_ratio(normalized1, normalized2)
    token_sort = fuzz.token_sort_ratio(normalized1, normalized2)

    return (ratio + partial_ratio + token_sort) / 300  # Normalize to 0-1

import re

def rule_based_vehicle_match(vehicle1, vehicle2):
    score = 0.0
    max_score = 1.0

    # Extract components (simplified - you might want more sophisticated parsing)
    def extract_components(vehicle_str):
        # This is simplified - consider using proper vehicle parsing libraries
        words = vehicle_str.lower().split()
        return {
            'brand': words[0] if words else '',
            'model': ' '.join(words[1:]) if len(words) > 1 else ''
        }

    comp1 = extract_components(vehicle1)
    comp2 = extract_components(vehicle2)

    # Brand matching (highest weight)
    if comp1['brand'] and comp2['brand']:
        if comp1['brand'] == comp2['brand']:
            score += 0.6  # Brand match is crucial
        elif comp1['brand'] in comp2['brand'] or comp2['brand'] in comp1['brand']:
            score += 0.4  # Partial brand match

    # Model matching
    if comp1['model'] and comp2['model']:
        model_similarity = fuzz.ratio(comp1['model'], comp2['model']) / 100
        score += model_similarity * 0.4

    return min(score, max_score)

def hybrid_matching_score(vehicle1, vehicle2, weights=None):
    if weights is None:
        weights = {'fuzzy': 0.3, 'embedding': 0.4, 'rules': 0.3}

    # Multiple scoring methods
    fuzzy_score = fuzzy_match_score(vehicle1, vehicle2)
    embedding_score = get_matching_score(vehicle1, vehicle2)
    rule_score = rule_based_vehicle_match(vehicle1, vehicle2)

    # Weighted combination
    final_score = (weights['fuzzy'] * fuzzy_score +
                   weights['embedding'] * embedding_score +
                   weights['rules'] * rule_score)

    return {
        'final_score': final_score,
        'components': {
            'fuzzy': fuzzy_score,
            'embedding': embedding_score,
            'rules': rule_score
        }
    }

# For more sophisticated matching, use models trained on similar tasks
from sentence_transformers import CrossEncoder

# Use a model trained on semantic textual similarity
model = CrossEncoder('cross-encoder/stsb-roberta-base')

def cross_encoder_score(text1, text2):
    scores = model.predict([[text1, text2]])
    return float(scores[0])